#!/usr/bin/env python3

#--------------------------------------------------------------------------
# Visualization model of the IRB 6600-225 6axis serial manipulator
#--------------------------------------------------------------------------


from vismach import *
import hal

c = hal.component("abb-gui")
c.newpin("joint1", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint2", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint3", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint4", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint5", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint6", hal.HAL_FLOAT, hal.HAL_IN)
c.ready()


###################

# show CNC-tooltip position (tool trace in window)
tooltip = Capture()
tool = CylinderZ(0, 5, 136, 8)

try: # Expect files in working directory
    # create toolholder from file
    link6 = AsciiSTL(filename="cad/link6.ast")
    link6 = Color([0.855,0.392,0.106,1],[link6])
    # create wrist from file
    link5 = AsciiSTL(filename="cad/link5.ast")
    link5 = Color([0.855,0.392,0.106,1],[link5])
    # create forearm from file
    link4 = AsciiSTL(filename="cad/link4.ast")
    link4 = Color([0.855,0.392,0.106,1],[link4])
    # create ellbow trom file
    link3 = AsciiSTL(filename="cad/link3.ast")
    link3 = Color([0.855,0.392,0.106,1],[link3])
    # create upper arm from file
    link2 = AsciiSTL(filename="cad/link2.ast")
    link2 = Color([0.855,0.392,0.106,1],[link2])
    # create shoulder from file
    link1 = AsciiSTL(filename="cad/link1.ast")
    link1 = Color([0.855,0.392,0.106,1],[link1])
    # create base (waist) from file
    link0 = AsciiSTL(filename="cad/link0.ast")
    link0 = Color([0.855,0.392,0.106,1],[link0])
except Exception as detail:
    print(detail)
    raise SystemExit("abb-gui requires files link[0-6].ast in working directory")


# combine tool and coordinate axis = tool-assembly
tool = Collection([tool,tooltip])

# translate tool-assembly so tool mounting point is in origin
tool = Translate([tool],0,0,-136)

# rotate link6 model into the correct orientation
link6 = Rotate([link6],90,0,1,0)

# combine tool-assembly to toolholder = hand-assembly
link6 = Collection([tool,link6])
# create HAL-link for Joint6 "Hand rotation"
link6 = HalRotate([link6],c,"joint6",1,0,0,1)

# translate hand-assembly so joint6 rotation is in origin
link6 = Translate([link6],0,0,-163)

# rotate link5 model into the correct orientation
link5 = Rotate([link5],90,0,1,0)

# combine hand-assembly to wrist = wrist-assembly
link5 = Collection([link6, link5])
# create HAL-link for Joint5 "Wrist rotation"
link5 = HalRotate([link5],c,"joint5",1,0,1,0)

# translate wrist-assembly so joint5 rotation is in origin
link5 = Translate([link5],0,0,-912)

# rotate link4 model into the correct orientation
link4 = Rotate([link4],90,1,0,0)
link4 = Rotate([link4],90,0,1,0)
link4 = Rotate([link4],90,0,0,1)

# connect wrist-assembly to forearm = forearm-assembly
link4 = Collection([link5, link4])
# create HAL-link for Joint4 "Forearm rotation"
link4 = HalRotate([link4],c,"joint4",1,0,0,1)

# translate forearm-assembly so joint4 rotation is in origin
link4 = Translate([link4],200,0,-230)

# rotate link3 model into the correct orientation
link3 = Rotate([link3],90,0,1,0)

# combine the forearm-assembly to the ellbow = ellbow-assembly
link3 = Collection([link4, link3])
# create HAL-link for Joint3 "Ellbow rotation"
link3 = HalRotate([link3],c,"joint3",1,0,1,0)

# translate ellbow-assembly so joint3 rotation is in the origin
link3 = Translate([link3],1075,0,0)

# rotate link2 model into the correct orientation
link2 = Rotate([link2],90,0,1,0)

# connect the ellbow-assembly to the upper arm = upper-arm-assembly
link2 = Collection([link3, link2])
# create HAL-link for Joint2 "Shoulder rotation"
link2 = HalRotate([link2],c,"joint2",1,0,1,0)

# translate upper-arm-assembly so joint2 rotation is in the origin
link2 = Translate([link2],320,0,780)

# combine the upper-arm-assembly to the shoulder = shoulder-assembly
link1 = Collection([link2, link1])
# create HAL-link for Joint1 "Waist rotation"
link1 = HalRotate([link1],c,"joint1",1,0,0,-1)

# combine the shoulder-assembly to the base = robot
robot = Collection([link1, link0])


# add a floor
floor = Box(-1500,-1500,-1,1500,1500,0.0)
floor = Color([0.5,0.5,0.5,1],[floor])

# finalize and show
work = Capture()
model = Collection([robot,floor,work])

# main call
main(model, tooltip, work, size=3000, lat=-60, lon=-60)
